import type { ProjectDefinition, SourceDefinition, ToolDefinition } from '../../../../engine/contracts';
import { calculateHiringProfit, formatPercent, formatWon } from './calculator';
const exampleInput = { employeeMonthlyCost: 3_000_000, variableRate: 0.35, operatingDays: 26, currentDailyRevenue: 500_000 };
const exampleResult = calculateHiringProfit(exampleInput);
export const hiringProfitSources: SourceDefinition[] = [{ id: 'sajang-hiring-profit-spec', title: '사장도구 직원 고용 손익 계산 명세' }];
export const hiringProfitTool: ToolDefinition = {
 identity: { id: 'hiring-profit', slug: 'hiring-profit', category: 'hiring', status: 'published', version: '0.1.0' },
 search: { question: '한 명 더 써도 될까?', name: '직원 고용 손익 계산기', title: '직원 고용 손익 계산기 - 한 명 더 써도 될까? | 사장도구', description: '추가 직원 월 총비용과 평균 변동비율을 기준으로 필요한 추가 월매출과 하루 매출을 계산합니다.' },
 knowledge: { exampleInputDisplay: { variableRate: formatPercent(exampleInput.variableRate) }, exampleLabels: { inputs: { employeeMonthlyCost: '추가 직원 월 총비용', variableRate: '평균 변동비율', operatingDays: '월 영업일', currentDailyRevenue: '현재 하루 평균 매출' }, result: { contributionRate: '비용을 빼고 남는 비율', additionalMonthlyRevenue: '추가 필요 월매출', additionalDailyRevenue: '추가 필요 하루 매출', requiredIncreaseRate: '필요한 매출 증가율' } }, shortAnswer: '직원 한 명의 월 총비용과 평균 변동비율, 영업일을 입력하면 해당 비용을 감당하기 위해 필요한 추가 월매출과 하루 매출을 계산합니다.', definition: '직원 고용 손익 계산기는 사용자가 판단한 추가 직원 월 총비용을 현재 사업의 비용을 빼고 남는 비율로 감당하려면 추가 매출이 얼마나 필요한지 계산합니다.', howItWorks: '매출에서 변동비를 제외한 비용을 빼고 남는 비율을 구한 뒤 추가 직원 월 총비용을 비용을 빼고 남는 비율로 나누어 추가 필요 월매출을 계산합니다. 이를 월 영업일로 나누면 하루 추가 필요 매출이 됩니다. 현재 하루 평균 매출을 입력하면 필요한 매출 증가율도 확인합니다.', formula: '비용을 빼고 남는 비율 = 1 - 평균 변동비율\n추가 필요 월매출 = 추가 직원 월 총비용 / 비용을 빼고 남는 비율\n추가 필요 하루 매출 = 추가 필요 월매출 / 월 영업일\n필요한 매출 증가율 = 추가 필요 하루 매출 / 현재 하루 평균 매출', example: { title: '추가 직원 월 총비용 3,000,000원, 평균 변동비율 35%, 월 영업일 26일, 현재 하루 평균 매출 500,000원', inputs: exampleInput, result: { contributionRate: formatPercent(exampleResult.contributionRate), additionalMonthlyRevenue: formatWon(exampleResult.additionalMonthlyRevenue), additionalDailyRevenue: formatWon(exampleResult.additionalDailyRevenue), requiredIncreaseRate: formatPercent(exampleResult.requiredIncreaseRate ?? 0) }, explanation: `계산 결과 추가 필요 월매출 ${formatWon(exampleResult.additionalMonthlyRevenue)}, 하루 추가 필요 매출 ${formatWon(exampleResult.additionalDailyRevenue)}, 필요한 매출 증가율 ${formatPercent(exampleResult.requiredIncreaseRate ?? 0)}입니다.` }, limitations: ['사장도구의 계산 결과는 사용자가 입력한 조건을 기준으로 한 단순 추정입니다. 실제 사업 결과는 세금, 부가가치세, 금융비용, 환불, 폐기, 할인, 계절성 및 기타 비용 등에 따라 달라질 수 있습니다.', '노동관계법령에 따른 실제 인건비를 산정하는 급여 계산기가 아닙니다.', '생산성, 업무시간 감소, 서비스 품질, 운영 안정성 등은 이 단순 계산에 포함되지 않을 수 있습니다.'], faq: [{ question: '추가 직원 월 총비용에는 무엇을 입력하나요?', answer: '직원을 추가하면서 실제로 월별 부담한다고 판단한 전체 비용을 입력합니다. 급여 외에 사용자가 부담한다고 보는 비용을 포함할 수 있지만 법정 요율을 자동 계산하지는 않습니다.' }, { question: '현재 하루 평균 매출을 입력하지 않아도 되나요?', answer: '네. 추가 필요 월매출과 하루 매출은 계산할 수 있고, 현재 하루 평균 매출을 입력하면 필요한 매출 증가율을 계산합니다.' }], },
 interaction: { inputs: [], outputs: [], calculator: 'hiring-profit' }, relations: { relatedTools: [], relatedDecisions: [{ toolId: 'daily-sales-target', question: '추가 매출 목표를 달성할 수 있을까요?', label: '하루 목표 매출을 함께 확인해보세요.' }, { toolId: 'price-change', question: '가격 변경으로 추가 매출을 만들 수 있을까요?', label: '가격 변경에 따른 판매량 변화를 확인해보세요.' }], sources: ['sajang-hiring-profit-spec'] }, maintenance: { reviewedAt: '2026-09-08' },
};
export const hiringProfitProject: ProjectDefinition = { id: 'sajang', name: '사장도구', description: '장사를 하며 필요한 숫자를 계산하는 도구', locale: 'ko-KR', baseUrl: '/', owner: 'Sajang', navigation: [], features: { localStorage: false, analytics: false, ads: false, remoteData: false }, theme: { id: 'working-ledger' }, categories: [{ id: 'hiring', name: '고용', question: '한 명 더 써도 될까?', description: '추가 직원 비용과 필요한 매출을 계산합니다.', tools: ['hiring-profit'], status: 'published' }], tools: [hiringProfitTool], sources: hiringProfitSources };
