import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { calculateDiscountProfit, DiscountProfitInputError } from '../src/projects/sajang/tools/discount-profit/calculator';
import { discountProfitTool } from '../src/projects/sajang/tools/discount-profit/definition';

const base = { regularPrice: 20_000, currentQuantity: 100, unitCost: 10_000, fixedSellingCost: 1_000, percentageFee: 0.05 };
describe('discount-profit production calculator', () => {
  it('calculates discount price, contributions, required quantity and increase rate', () => { const result = calculateDiscountProfit({ ...base, discountRate: 0.1 }); expect(result.discountPrice).toBe(18_000); expect(result.currentUnitContribution).toBe(8_000); expect(result.currentTotalContribution).toBe(800_000); expect(result.discountUnitContribution).toBe(6_100); expect(result.requiredQuantity).toBeCloseTo(131.1475, 4); expect(result.requiredIncreaseRate).toBeCloseTo(0.31147, 4); });
  it('handles zero discount without error and preserves the baseline', () => { const result = calculateDiscountProfit({ ...base, discountRate: 0 }); expect(result.discountPrice).toBe(base.regularPrice); expect(result.requiredQuantity).toBe(base.currentQuantity); expect(result.requiredIncreaseRate).toBe(0); });
  it('rejects 100 percent discount when the resulting contribution is non-positive', () => { expect(() => calculateDiscountProfit({ ...base, discountRate: 1 })).toThrow('DISCOUNT_CONTRIBUTION_NOT_POSITIVE'); });
  it('rejects zero or negative contributions, quantities, prices and rates', () => { expect(() => calculateDiscountProfit({ ...base, unitCost: 9_000, fixedSellingCost: 10_000, discountRate: 0.1 })).toThrow('CURRENT_CONTRIBUTION_NOT_POSITIVE'); expect(() => calculateDiscountProfit({ ...base, discountRate: 0.5, unitCost: 10_000, fixedSellingCost: 8_000 })).toThrow('DISCOUNT_CONTRIBUTION_NOT_POSITIVE'); expect(() => calculateDiscountProfit({ ...base, currentQuantity: 0, discountRate: 0 })).toThrow('INVALID_CURRENT_QUANTITY'); expect(() => calculateDiscountProfit({ ...base, regularPrice: 0, discountRate: 0 })).toThrow('INVALID_REGULAR_PRICE'); expect(() => calculateDiscountProfit({ ...base, discountRate: -0.01 })).toThrow('INVALID_DISCOUNT_RATE'); expect(() => calculateDiscountProfit({ ...base, percentageFee: 1, discountRate: 0 })).toThrow('INVALID_PERCENTAGE_FEE'); });
  it('protects non-finite input and finite overflow', () => { expect(() => calculateDiscountProfit({ ...base, regularPrice: Number.NaN, discountRate: 0 })).toThrow(DiscountProfitInputError); expect(() => calculateDiscountProfit({ regularPrice: 1e308, currentQuantity: 1e308, unitCost: 0, fixedSellingCost: 0, percentageFee: 0, discountRate: 0 })).toThrow('NON_FINITE_RESULT'); });
  it('keeps static example parity, content contract and sitemap inclusion', () => { const definition = readFileSync('src/projects/sajang/tools/discount-profit/definition.ts', 'utf8'); const page = readFileSync('src/pages/tools/discount-profit.astro', 'utf8'); const sitemap = readFileSync('src/pages/sitemap.xml.ts', 'utf8'); const client = readFileSync('src/projects/sajang/tools/discount-profit/client.ts', 'utf8'); for (const section of ['shortAnswer', 'definition', 'howItWorks', 'formula', 'example', 'limitations', 'faq', 'relatedDecisions', 'sources']) expect(definition).toContain(section); expect(discountProfitTool.knowledge.example.result.discountPrice).toBe('18,000원'); expect(discountProfitTool.knowledge.example.result.requiredQuantity).toBe('132개'); expect(page).toContain('ToolKnowledgePage'); expect(page).toContain('필요한 판매량'); expect(client).toContain('setFiniteResult'); expect(client).toContain('aria-describedby'); expect(sitemap).toContain('discountProfitTool'); });
});
