import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { calculateHiringProfit, HiringProfitInputError } from '../src/projects/sajang/tools/hiring-profit/calculator';
import { hiringProfitTool } from '../src/projects/sajang/tools/hiring-profit/definition';
const base = { employeeMonthlyCost: 3_000_000, variableRate: 0.35, operatingDays: 26 };
describe('hiring-profit production calculator', () => {
  it('calculates contribution and additional monthly/daily revenue', () => { const result = calculateHiringProfit({ ...base, currentDailyRevenue: 500_000 }); expect(result.contributionRate).toBe(0.65); expect(result.additionalMonthlyRevenue).toBeCloseTo(4_615_384.615, 3); expect(result.additionalDailyRevenue).toBeCloseTo(177_514.792, 2); expect(result.requiredIncreaseRate).toBeCloseTo(0.355029, 5); });
  it('keeps blank current revenue distinct from zero', () => { expect(calculateHiringProfit(base).requiredIncreaseRate).toBeUndefined(); expect(calculateHiringProfit({ ...base, currentDailyRevenue: 0 }).requiredIncreaseRate).toBeUndefined(); });
  it('allows zero employee cost', () => { const result = calculateHiringProfit({ ...base, employeeMonthlyCost: 0, currentDailyRevenue: 500_000 }); expect(result.additionalMonthlyRevenue).toBe(0); expect(result.additionalDailyRevenue).toBe(0); expect(result.requiredIncreaseRate).toBe(0); });
  it('rejects invalid cost, rates and operating days', () => { expect(() => calculateHiringProfit({ ...base, employeeMonthlyCost: -1 })).toThrow('INVALID_EMPLOYEE_COST'); expect(() => calculateHiringProfit({ ...base, variableRate: -0.01 })).toThrow('INVALID_VARIABLE_RATE'); expect(() => calculateHiringProfit({ ...base, variableRate: 1 })).toThrow('INVALID_VARIABLE_RATE'); expect(() => calculateHiringProfit({ ...base, operatingDays: 0 })).toThrow('INVALID_OPERATING_DAYS'); expect(() => calculateHiringProfit({ ...base, operatingDays: 32 })).toThrow('INVALID_OPERATING_DAYS'); expect(() => calculateHiringProfit({ ...base, currentDailyRevenue: -1 })).toThrow('INVALID_CURRENT_DAILY_REVENUE'); });
  it('rejects no-contribution boundaries without Infinity', () => { expect(() => calculateHiringProfit({ ...base, variableRate: 1 })).toThrow('INVALID_VARIABLE_RATE'); expect(() => calculateHiringProfit({ ...base, variableRate: 0.999999999 })).not.toThrow(); });
  it('protects non-finite input and finite overflow', () => { expect(() => calculateHiringProfit({ ...base, employeeMonthlyCost: Number.NaN })).toThrow(HiringProfitInputError); expect(() => calculateHiringProfit({ employeeMonthlyCost: 1e308, variableRate: 0.9999999999999999, operatingDays: 1, currentDailyRevenue: undefined })).toThrow('NON_FINITE_RESULT'); });
  it('keeps static parity, limitation, contract and sitemap inclusion explicit', () => { const definition = readFileSync('src/projects/sajang/tools/hiring-profit/definition.ts', 'utf8'); const page = readFileSync('src/pages/tools/hiring-profit.astro', 'utf8'); const client = readFileSync('src/projects/sajang/tools/hiring-profit/client.ts', 'utf8'); const sitemap = readFileSync('src/pages/sitemap.xml.ts', 'utf8'); for (const section of ['shortAnswer', 'definition', 'howItWorks', 'formula', 'example', 'limitations', 'faq', 'relatedDecisions', 'sources']) expect(definition).toContain(section); expect(definition).toContain('노동관계법령에 따른 실제 인건비를 산정하는 급여 계산기가 아닙니다.'); expect(hiringProfitTool.knowledge.example.result.additionalDailyRevenue).toBe('177,515원'); expect(page).toContain('ToolKnowledgePage'); expect(client).toContain('setFiniteResult'); expect(client).toContain('aria-describedby'); expect(sitemap).toContain('hiringProfitTool'); });
});
