import { calculateDiscountProfit, DiscountProfitInputError, formatPercent, formatQuantity, formatWon } from './calculator';
import { setFiniteResult } from '../../../../engine/result-runtime';
const form = document.querySelector<HTMLFormElement>('[data-discount-profit-form]');
if (form) {
  const root = form.closest('[data-discount-profit-tool]');
  const result = (name: string) => root?.querySelector<HTMLElement>(`[data-result="${name}"]`);
  const primary = root?.querySelector<HTMLElement>('#required-quantity-result [data-result-number]');
  const clearResults = () => root?.querySelectorAll<HTMLElement>('[data-result-value], [data-result], [data-calculator-meaning]').forEach((element) => { element.textContent = '—'; });
  const clearErrors = () => form.querySelectorAll<HTMLElement>('[data-input-field]').forEach((field) => { const input = field.querySelector<HTMLInputElement>('input'); input?.setAttribute('aria-invalid', 'false'); input?.setAttribute('aria-describedby', input?.dataset.descriptionId ?? ''); const error = field.querySelector<HTMLElement>('[data-input-error]'); if (error) { error.textContent = ''; error.hidden = true; } });
  const showError = (ids: string[], message: string) => ids.forEach((id) => { const field = form.querySelector<HTMLElement>(`[data-input-field="${id}"]`); const input = field?.querySelector<HTMLInputElement>('input'); const error = field?.querySelector<HTMLElement>('[data-input-error]'); input?.setAttribute('aria-invalid', 'true'); if (input) input.setAttribute('aria-describedby', [input.dataset.descriptionId, input.dataset.errorId].filter(Boolean).join(' ')); if (error) { error.textContent = message; error.hidden = false; } });
  const read = (name: string) => { const value = new FormData(form).get(name); return value === null || value === '' ? undefined : Number(value); };
  form.addEventListener('invalid', (event) => { clearResults(); clearErrors(); showError([(event.target as HTMLInputElement).id], '이 항목의 입력값을 확인해주세요.'); }, true);
  form.addEventListener('submit', (event) => { event.preventDefault(); clearResults(); clearErrors(); try { const calculation = calculateDiscountProfit({ regularPrice: Number(read('regularPrice')), currentQuantity: Number(read('currentQuantity')), unitCost: Number(read('unitCost')), fixedSellingCost: Number(read('fixedSellingCost')), percentageFee: Number(read('percentageFee')) / 100, discountRate: Number(read('discountRate')) / 100 }); if (primary) setFiniteResult(primary, calculation.requiredQuantity, formatQuantity); setFiniteResult(result('discountPrice')!, calculation.discountPrice, formatWon); setFiniteResult(result('currentUnitContribution')!, calculation.currentUnitContribution, formatWon); setFiniteResult(result('discountUnitContribution')!, calculation.discountUnitContribution, formatWon); setFiniteResult(result('currentTotalContribution')!, calculation.currentTotalContribution, formatWon); const meaning = root?.querySelector<HTMLElement>('[data-calculator-meaning]'); if (meaning) meaning.textContent = calculation.requiredIncreaseRate === 0 ? '할인하지 않으므로 현재와 같은 판매량이 필요합니다.' : `할인 후 현재 총 기여금을 유지하려면 판매량이 ${formatPercent(calculation.requiredIncreaseRate)} 증가해야 합니다.`; } catch (caught) { clearResults(); const code = caught instanceof DiscountProfitInputError ? caught.code : 'NON_FINITE_INPUT'; const field = code.includes('REGULAR_PRICE') ? 'regularPrice' : code.includes('CURRENT_QUANTITY') ? 'currentQuantity' : code.includes('UNIT_COST') ? 'unitCost' : code.includes('FIXED_SELLING_COST') ? 'fixedSellingCost' : code.includes('PERCENTAGE_FEE') ? 'percentageFee' : code.includes('DISCOUNT_RATE') ? 'discountRate' : undefined; const messageText = code === 'DISCOUNT_CONTRIBUTION_NOT_POSITIVE' ? '할인 후 개당 기여금이 0 이하이므로 판매량을 늘리는 것만으로 현재 총 기여금을 유지할 수 없습니다.' : code === 'CURRENT_CONTRIBUTION_NOT_POSITIVE' ? '할인 전 개당 기여금이 0 이하이므로 비교 기준으로 사용할 수 없습니다.' : '이 입력값을 확인해주세요.'; if (field) showError([field], messageText); else { const message = form.querySelector<HTMLElement>('[data-calculator-error]'); if (message) { message.textContent = messageText; message.hidden = false; } } } });
}
