import { calculatePriceChange, formatPercent, formatQuantity, formatWon, PriceChangeInputError } from './calculator';
import { setFiniteResult } from '../../../../engine/result-runtime';

const form = document.querySelector<HTMLFormElement>('[data-price-change-form]');
if (form) {
  const result = (name: string) => form.closest('[data-price-change-tool]')?.querySelector<HTMLElement>(`[data-result="${name}"]`);
  const primary = form.closest('[data-price-change-tool]')?.querySelector<HTMLElement>('#required-quantity-result [data-result-number]');
  const clearErrors = () => form.querySelectorAll<HTMLElement>('[data-input-field]').forEach((field) => { const input = field.querySelector<HTMLInputElement>('input'); input?.setAttribute('aria-invalid', 'false'); input?.setAttribute('aria-describedby', input?.dataset.descriptionId ?? ''); const error = field.querySelector<HTMLElement>('[data-input-error]'); if (error) { error.textContent = ''; error.hidden = true; } });
  const clearResults = () => form.closest('[data-price-change-tool]')?.querySelectorAll<HTMLElement>('[data-result-value], [data-result], [data-calculator-meaning]').forEach((element) => { element.textContent = '—'; });
  const showError = (ids: string[], message: string) => ids.forEach((id) => { const field = form.querySelector<HTMLElement>(`[data-input-field="${id}"]`); const input = field?.querySelector<HTMLInputElement>('input'); const error = field?.querySelector<HTMLElement>('[data-input-error]'); input?.setAttribute('aria-invalid', 'true'); if (input) input.setAttribute('aria-describedby', [input.dataset.descriptionId, input.dataset.errorId].filter(Boolean).join(' ')); if (error) { error.textContent = message; error.hidden = false; } });
  const read = (name: string) => { const raw = new FormData(form).get(name); return raw === null || raw === '' ? undefined : Number(raw); };
  form.addEventListener('invalid', (event) => { clearResults(); clearErrors(); showError([(event.target as HTMLInputElement).id], '이 항목의 입력값을 확인해주세요.'); }, true);
  form.addEventListener('submit', (event) => { event.preventDefault(); clearResults(); clearErrors(); try { const input = { currentPrice: Number(read('currentPrice')), currentQuantity: Number(read('currentQuantity')), unitCost: Number(read('unitCost')), fixedSellingCost: Number(read('fixedSellingCost')), percentageFee: Number(read('percentageFee')) / 100, newPrice: Number(read('newPrice')), expectedQuantity: read('expectedQuantity') }; const calculation = calculatePriceChange(input); if (primary) setFiniteResult(primary, calculation.requiredQuantity, formatQuantity); setFiniteResult(result('currentUnitContribution')!, calculation.currentUnitContribution, formatWon); setFiniteResult(result('newUnitContribution')!, calculation.newUnitContribution, formatWon); setFiniteResult(result('currentTotalContribution')!, calculation.currentTotalContribution, formatWon); setFiniteResult(result('expectedTotalContribution')!, calculation.expectedTotalContribution ?? NaN, formatWon); setFiniteResult(result('contributionChange')!, calculation.contributionChange ?? NaN, formatWon); const meaning = form.closest('[data-price-change-tool]')?.querySelector<HTMLElement>('[data-calculator-meaning]'); if (meaning) meaning.textContent = calculation.priceDirection === 'same' ? '가격 변화가 없으므로 일반적으로 현재와 같은 판매량이 필요합니다.' : calculation.quantityChangeRate < 0 ? `현재 총 기여금을 유지하려면 판매량이 ${formatPercent(Math.abs(calculation.quantityChangeRate))} 감소해도 됩니다.` : `현재 총 기여금을 유지하려면 판매량이 ${formatPercent(calculation.quantityChangeRate)} 증가해야 합니다.`; } catch (caught) { const code = caught instanceof PriceChangeInputError ? caught.code : 'NON_FINITE_INPUT'; clearResults(); const field = code.includes('CURRENT_PRICE') ? 'currentPrice' : code.includes('CURRENT_QUANTITY') ? 'currentQuantity' : code.includes('UNIT_COST') ? 'unitCost' : code.includes('FIXED_SELLING_COST') ? 'fixedSellingCost' : code.includes('PERCENTAGE_FEE') ? 'percentageFee' : code.includes('NEW_PRICE') ? 'newPrice' : code.includes('EXPECTED_QUANTITY') ? 'expectedQuantity' : undefined; const messageText = code === 'NEW_CONTRIBUTION_NOT_POSITIVE' ? '변경 후 개당 기여금이 0 이하이므로 판매량 증가만으로 현재 총 기여금을 유지할 수 없습니다.' : code === 'CURRENT_CONTRIBUTION_NOT_POSITIVE' ? '현재 개당 기여금이 0 이하이므로 비교 기준으로 사용할 수 없습니다.' : '이 입력값을 확인해주세요.'; if (field) showError([field], messageText); else { const message = form.querySelector<HTMLElement>('[data-calculator-error]'); if (message) { message.textContent = messageText; message.hidden = false; } } } });
}
